export default {
  NOMBRE_JGM: 'Jefatura de Gabinete',
  CAMARAS: {
    HSN: 'HSN',
    HCDN: 'HCDN'
  },
  ESTADOS_RESPUESTA_DERIVACION: {
    PENDIENTE: 1,
    ACEPTADA: 2,
    RECHAZADA: 3
  },
  ESTADOS_INFORME: {
    PENDIENTE: 1,
    CONFIRMADO: 2,
    CERRADO: 3,
    DEFINITIVO: 4
  },
  ESTADOS_DERIVACION: {
    PENDIENTE_CONFIRMACION: 1,
    PENDIENTE_ACEPTACION: 2,
    PENDIENTE_RESPUESTA: 3,
    RECHAZADA: 4,
    RESPONDIDA: 5,
    TERMINADA: 6
  },
  ESTADOS_PREGUNTA_ORIGINAL: {
    PENDIENTE: 1,
    ACEPTADA: 2,
    UNIFICADA: 3,
    NO_APLICA: 4,
    RECHAZADA: 5,
  },
  ESTADOS_PREGUNTA_CONSOLIDADA: {
    PENDIENTE: 1,
    DERIVADA: 2,
    RESPONDIDA: 3
  },
  MOTIVOS_CONSOLIDACION: {
    MOTIVO_1: 1,
    MOTIVO_2: 2,
    MOTIVO_3: 3
  },
  TIPOS_NOTA: {
    NOTA: 'NOTA',
    ACEPTACION_PREGUNTA: 'ACEPTACION PREGUNTA',
    RECHAZO_PREGUNTA: 'RECHAZO PREGUNTA',
    ACEPTACION_RESPUESTA: 'ACEPTACION RESPUESTA',
    RECHAZO_RESPUESTA: 'RECHAZO_RESPUESTA',
    REDERIVACION: 'REDERIVACION'
  }
}